version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - /data/pgsql:/var/lib/pgsql
    env_file: .env
  pizzeria:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pizzeria
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: DockerfileProduction
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/pizzeria
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - pizzeria