version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - /data/pgsql:/var/lib/pgsql
    env_file: .env
  pizzeria:
    volumes:
      - .:/pizzeria
      - ~/.ssh:/root/.ssh
      - /tmp:/tmp
      #- ./site.conf:/etc/nginx/sites-enabled/myapp.conf
    ports:
      - "80:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: DockerfileProduction
